function makeId() {
  return Math.random().toString(36).slice(2, 11) + Date.now().toString(36);
}

export const SEED_CARDS = [
  {
    id: makeId(),
    name: 'Sample Card A',
    balance: 5000,
    originalBalance: 5000,
    apr: 0,
    promoExpiration: '2027-06-01',
    postPromoApr: 0.2699,
    monthlyPayment: 417,
    dueDate: 1,
    payStatus: 'Pending',
    lastPaymentDate: null,
    lastPaymentAmount: 0,
    paymentHistory: [],
    notes: '',
    isTransferred: false,
    transferFee: 0,
    notificationEnabled: false,
    notificationDaysBefore: 60,
    notificationMode: 'days',
    notificationCustomDate: null,
    notificationCustomMessage: '',
    monthlyReminderEnabled: false,
    monthlyReminderDaysBefore: 3,
  },
  {
    id: makeId(),
    name: 'Sample Card B',
    balance: 3000,
    originalBalance: 3000,
    apr: 0,
    promoExpiration: '2027-03-01',
    postPromoApr: 0.2699,
    monthlyPayment: 250,
    dueDate: 15,
    payStatus: 'Pending',
    lastPaymentDate: null,
    lastPaymentAmount: 0,
    paymentHistory: [],
    notes: '',
    isTransferred: false,
    transferFee: 0,
    notificationEnabled: false,
    notificationDaysBefore: 60,
    notificationMode: 'days',
    notificationCustomDate: null,
    notificationCustomMessage: '',
    monthlyReminderEnabled: false,
    monthlyReminderDaysBefore: 3,
  },
  {
    id: makeId(),
    name: 'Sample Card C',
    balance: 1500,
    originalBalance: 1500,
    apr: 0,
    promoExpiration: '2026-12-01',
    postPromoApr: 0.2699,
    monthlyPayment: 125,
    dueDate: 10,
    payStatus: 'Pending',
    lastPaymentDate: null,
    lastPaymentAmount: 0,
    paymentHistory: [],
    notes: '',
    isTransferred: false,
    transferFee: 0,
    notificationEnabled: false,
    notificationDaysBefore: 60,
    notificationMode: 'days',
    notificationCustomDate: null,
    notificationCustomMessage: '',
    monthlyReminderEnabled: false,
    monthlyReminderDaysBefore: 3,
  },
];

// ─── Bill categories ───────────────────────────────────────────────────────────
// Auto | Insurance | Loans | Utilities | Subscriptions | Health | Other

export const SEED_FIXED_BILLS = [
  {
    id: makeId(),
    name: 'Car Payment',
    amount: 400,
    isVariable: false,
    variableAmountThisMonth: null,
    dueDate: 15,
    payStatus: 'Pending',
    category: 'Auto',
    lastPaymentDate: null,
    lastPaymentAmount: 0,
    paymentHistory: [],
    notificationEnabled: false,
    notificationDaysBefore: 3,
    customReminderEnabled: false,
    customReminderDate: null,
    customReminderMessage: '',
  },
  {
    id: makeId(),
    name: 'Car Insurance',
    amount: 150,
    isVariable: false,
    variableAmountThisMonth: null,
    dueDate: 1,
    payStatus: 'Pending',
    category: 'Insurance',
    lastPaymentDate: null,
    lastPaymentAmount: 0,
    paymentHistory: [],
    notificationEnabled: false,
    notificationDaysBefore: 3,
    customReminderEnabled: false,
    customReminderDate: null,
    customReminderMessage: '',
  },
  {
    id: makeId(),
    name: 'Electric',
    amount: 100,
    isVariable: true,
    variableAmountThisMonth: null,
    dueDate: 20,
    payStatus: 'Pending',
    category: 'Utilities',
    lastPaymentDate: null,
    lastPaymentAmount: 0,
    paymentHistory: [],
    notificationEnabled: false,
    notificationDaysBefore: 3,
    customReminderEnabled: false,
    customReminderDate: null,
    customReminderMessage: '',
  },
  {
    id: makeId(),
    name: 'Streaming',
    amount: 20,
    isVariable: false,
    variableAmountThisMonth: null,
    dueDate: 5,
    payStatus: 'Pending',
    category: 'Subscriptions',
    lastPaymentDate: null,
    lastPaymentAmount: 0,
    paymentHistory: [],
    notificationEnabled: false,
    notificationDaysBefore: 3,
    customReminderEnabled: false,
    customReminderDate: null,
    customReminderMessage: '',
  },
  {
    id: makeId(),
    name: 'Gym',
    amount: 30,
    isVariable: false,
    variableAmountThisMonth: null,
    dueDate: 1,
    payStatus: 'Pending',
    category: 'Health',
    lastPaymentDate: null,
    lastPaymentAmount: 0,
    paymentHistory: [],
    notificationEnabled: false,
    notificationDaysBefore: 3,
    customReminderEnabled: false,
    customReminderDate: null,
    customReminderMessage: '',
  },
];

export const SEED_SETTINGS = {
  monthlyIncome: 0,
  notificationsEnabled: false,
  notificationDaysAhead: 60,
  notificationMode: 'individual',
  digestTime: '09:00',
  privateNotifications: false,
  calendarSyncEnabled: false,
  calendarEventIds: {},
  dashboardBillsViewMode: 'list',
  biometricEnabled: false,
  autoLockTimeout: 5,
  requireBiometricExport: false,
  userName: '',
  checkingBalance: 0,
  savingsBalance: 0,
  extraPaymentPool: 0,
  cardOverrides: {},
  lastUpdatedMonth: `${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, '0')}`,
  lastUpdated: new Date().toISOString(),
};

export const defaultEmptySettings = {
  monthlyIncome: 0,
  checkingBalance: 0,
  savingsBalance: 0,
  extraPaymentPool: 0,
  cardOverrides: {},
  notificationsEnabled: false,
  notificationDaysAhead: 60,
  notificationMode: 'individual',
  digestTime: '09:00',
  privateNotifications: false,
  calendarSyncEnabled: false,
  calendarEventIds: {},
  dashboardBillsViewMode: 'list',
  biometricEnabled: false,
  autoLockTimeout: 5,
  requireBiometricExport: false,
  userName: '',
  lastUpdatedMonth: '',
  lastUpdated: new Date().toISOString(),
};
